import type { Board, Task } from './model';
import { parse, serialize, titleLine } from './markdown';
import type { Identity } from './auth';
import { authedFetch } from './api';

const HEALTH_TIMEOUT_MS = 1500;
const SAVE_DEBOUNCE_MS = 800;

type PendingSave = {
  identity: Identity;
  board: Board;
  onError?: (err: unknown) => void;
  onSuccess?: (pushed: Board) => void;
};

/**
 * Content identity of a task on the wire. Task ids are regenerated by parse()
 * (they are not serialized), so a refetched board cannot be matched by id —
 * the merge compares the lines the codec would write instead. The column is
 * deliberately NOT part of the identity: another surface running `kb done`
 * must read as the same card in a new column, not as one deletion plus one
 * arrival — the merge keeps both halves of that, duplicating the card.
 */
function taskKey(t: Task): string {
  const checks = t.checks.map((c) => `${c.done ? 'x' : ' '}${c.text}`).join('\n');
  // A NUL cannot appear in any field the codec accepts, so it is a safe
  // separator: two different tasks can never collide on one key.
  return [titleLine(t), t.desc, checks].join('\u0000');
}

/** taskKey plus the column — a task's full state as the codec writes it. */
function placedKey(t: Task): string {
  return `${t.status} ${taskKey(t)}`;
}

function countKeys(tasks: readonly Task[], into: Map<string, number>): void {
  for (const t of tasks) {
    const k = taskKey(t);
    into.set(k, (into.get(k) ?? 0) + 1);
  }
}

function pushKey(into: Map<string, Task[]>, key: string, t: Task): void {
  const bucket = into.get(key);
  if (bucket) bucket.push(t);
  else into.set(key, [t]);
}

/**
 * Resolve a 409: keep the local board, but carry over every server task the
 * client has never seen. `base` is the last server state this client observed;
 * a server task matching `base` or `local` is known to us (so a local delete
 * of it is a real delete and wins), anything else was written by another
 * client since and must never be dropped.
 *
 * A known task the server holds in another column was moved by another
 * surface. When our copy still sits exactly where we last read it we never
 * touched it, so that move is taken; when we moved it ourselves the local
 * edit wins, as it does for every other field.
 */
export function mergeBoards(
  local: Board,
  server: Board,
  base: Board | null,
): Board {
  const known = new Map<string, number>();
  if (base) countKeys(base.tasks, known);
  countKeys(local.tasks, known);
  // Local tasks still identical to the last server state we read, by identity:
  // only these may take a column change from the server.
  const pristine = new Map<string, Task[]>();
  if (base) {
    const placed = new Set(base.tasks.map(placedKey));
    for (const t of local.tasks) {
      if (placed.has(placedKey(t))) pushKey(pristine, taskKey(t), t);
    }
  }
  const extra: Task[] = [];
  const moved = new Map<Task, Task>();
  for (const t of server.tasks) {
    const k = taskKey(t);
    const n = known.get(k) ?? 0;
    if (n === 0) {
      extra.push(t);
      continue;
    }
    known.set(k, n - 1);
    const ours = pristine.get(k)?.shift();
    if (ours && ours.status !== t.status) moved.set(ours, t);
  }
  if (extra.length === 0 && moved.size === 0) return local;
  const tasks = local.tasks.map((t) => {
    const s = moved.get(t);
    return s ? { ...t, status: s.status, movedAt: s.movedAt } : t;
  });
  return { ...local, tasks: [...tasks, ...extra] };
}

export class RemoteStore {
  private saveTimer: ReturnType<typeof setTimeout> | null = null;
  private pending: PendingSave | null = null;
  /** Board version last seen from the server; sent back as If-Match. */
  private etag: string | null = null;
  /** Last server state this client observed — the merge base for a 409. */
  private base: Board | null = null;

  /** True when a kb server answers GET /api/health within ~1.5s. */
  async detect(): Promise<boolean> {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), HEALTH_TIMEOUT_MS);
    try {
      const res = await fetch('/api/health', { signal: ctrl.signal });
      if (!res.ok) return false;
      const body = (await res.json()) as { ok?: unknown };
      return body.ok === true;
    } catch {
      return false;
    } finally {
      clearTimeout(timer);
    }
  }

  /** null when the server has no board yet (404); throws on other failures. */
  async loadRemote(identity: Identity): Promise<Board | null> {
    const res = await authedFetch(identity, '/api/board');
    if (res.status === 404) {
      // The 404 carries the version of "no board", so keep it: without a
      // token our first PUT would be unconditional, and that write is the one
      // most likely to land on a board the CLI or MCP created meanwhile.
      this.etag = res.headers.get('ETag');
      this.base = null;
      return null;
    }
    if (!res.ok) throw new Error(`GET /api/board failed: ${res.status}`);
    const board = parse(await res.text());
    this.etag = res.headers.get('ETag');
    this.base = board;
    return board;
  }

  private putBoard(
    identity: Identity,
    board: Board,
    keepalive: boolean,
  ): Promise<Response> {
    const headers: Record<string, string> = { 'Content-Type': 'text/markdown' };
    // Optimistic concurrency: without a known version we cannot claim one, so
    // the server decides whether to accept an unconditional write.
    if (this.etag) headers['If-Match'] = this.etag;
    return authedFetch(identity, '/api/board', {
      method: 'PUT',
      headers,
      body: serialize(board),
      keepalive,
    });
  }

  /**
   * Fire-and-forget PUT of the serialized board. On a 409 (someone else wrote
   * since our last read) the server copy is refetched, merged so no unseen
   * task is dropped, and pushed once more. `onSuccess` receives the board that
   * actually reached the server — after a merge it differs from `board`, and
   * the caller must adopt it as clean state or the next save would delete the
   * merged-in tasks.
   */
  saveRemote(
    identity: Identity,
    board: Board,
    onError?: (err: unknown) => void,
    onSuccess?: (pushed: Board) => void,
    opts?: { keepalive?: boolean },
  ): void {
    const keepalive = opts?.keepalive ?? false;
    void (async () => {
      let pushed = board;
      let res = await this.putBoard(identity, pushed, keepalive);
      if (res.status === 409) {
        const base = this.base;
        // loadRemote refreshes etag/base, so the retry carries the version we
        // just merged against.
        const server = await this.loadRemote(identity);
        if (server) pushed = mergeBoards(board, server, base);
        res = await this.putBoard(identity, pushed, keepalive);
      }
      if (!res.ok) throw new Error(`PUT /api/board failed: ${res.status}`);
      this.base = pushed;
      // A server that echoes the new version lets the next save stay
      // conditional; without it the stale tag simply forces one more merge.
      const tag = res.headers.get('ETag');
      if (tag) this.etag = tag;
      onSuccess?.(pushed);
    })().catch((err: unknown) => onError?.(err));
  }

  /** Debounced (800ms) saveRemote — later calls replace pending ones. */
  saveRemoteDebounced(
    identity: Identity,
    board: Board,
    onError?: (err: unknown) => void,
    onSuccess?: (pushed: Board) => void,
  ): void {
    if (this.saveTimer !== null) clearTimeout(this.saveTimer);
    this.pending = { identity, board, onError, onSuccess };
    this.saveTimer = setTimeout(() => {
      const p = this.pending;
      this.saveTimer = null;
      this.pending = null;
      if (p) this.saveRemote(p.identity, p.board, p.onError, p.onSuccess);
    }, SAVE_DEBOUNCE_MS);
  }

  /**
   * Drop any pending debounced save without executing it — call on
   * unmount/sign-out so no PUT fires with a stale identity afterwards.
   */
  cancel(): void {
    if (this.saveTimer !== null) clearTimeout(this.saveTimer);
    this.saveTimer = null;
    this.pending = null;
  }

  /**
   * Execute any pending debounced save immediately. keepalive lets the PUT
   * outlive pagehide/tab close (bodies here are small markdown, well under
   * the keepalive body cap).
   */
  flush(): void {
    const p = this.pending;
    this.cancel();
    if (p) {
      this.saveRemote(p.identity, p.board, p.onError, p.onSuccess, {
        keepalive: true,
      });
    }
  }
}
