sonar.sources=.
sonar.tests=.
sonar.inclusions=**/*.go
sonar.test.inclusions=**/*_test.go,**/testdata/**/*.go
sonar.coverage.exclusions=**/testdata/**/*.go
sonar.go.coverage.reportPaths=coverage/go.out
sonar.sourceEncoding=UTF-8
