#!/usr/bin/env sh
# Compiles internal/webui/tailwind/app.css into internal/webui/static/app.css
# with the standalone Tailwind CLI. The output is committed; run this after
# editing the Tailwind source, index.html or app.js.
#
#   sh scripts/build-web-css.sh          rebuild static/app.css
#   sh scripts/build-web-css.sh --check  fail when the committed CSS is stale
#
# The CLI is downloaded once into the cache directory (override the binary
# with KB_TAILWIND_BIN). Only the linux-x64 build is hash pinned.
set -eu

version='v4.1.13'
linux_x64_sha256='b9ed9f8f640d3323711f9f68608aa266dff3adbc42e867c38ea2d009b973be11'

repo_root="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
source="$repo_root/internal/webui/tailwind/app.css"
target="$repo_root/internal/webui/static/app.css"
header='/* generated by scripts/build-web-css.sh from internal/webui/tailwind/app.css; do not edit */'
tmp=''

cleanup() {
  [ -z "$tmp" ] || rm -f -- "$tmp" "$tmp.raw"
}
trap cleanup EXIT HUP INT TERM

fail() {
  echo "web-css: $*" >&2
  exit 1
}

mode=build
case "${1:-}" in
  '') ;;
  --check) mode=check ;;
  *) fail "usage: build-web-css.sh [--check]" ;;
esac

[ -f "$source" ] || fail "missing $source"

platform() {
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  case "$os" in
    linux) os=linux ;;
    darwin) os=macos ;;
    *) fail "unsupported OS $os; set KB_TAILWIND_BIN" ;;
  esac
  case "$arch" in
    x86_64|amd64) arch=x64 ;;
    aarch64|arm64) arch=arm64 ;;
    *) fail "unsupported architecture $arch; set KB_TAILWIND_BIN" ;;
  esac
  echo "$os-$arch"
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d ' ' -f 1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d ' ' -f 1
  else
    echo ''
  fi
}

resolve_binary() {
  if [ -n "${KB_TAILWIND_BIN:-}" ]; then
    [ -x "$KB_TAILWIND_BIN" ] || fail "KB_TAILWIND_BIN is not executable: $KB_TAILWIND_BIN"
    echo "$KB_TAILWIND_BIN"
    return
  fi
  plat="$(platform)"
  cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/kb"
  bin="$cache_dir/tailwindcss-$version-$plat"
  if [ ! -x "$bin" ]; then
    url="https://github.com/tailwindlabs/tailwindcss/releases/download/$version/tailwindcss-$plat"
    mkdir -p -- "$cache_dir"
    echo "web-css: downloading $url" >&2
    if command -v curl >/dev/null 2>&1; then
      curl -fsSL -o "$bin.part" "$url" || fail "download failed"
    elif command -v wget >/dev/null 2>&1; then
      wget -q -O "$bin.part" "$url" || fail "download failed"
    else
      fail 'need curl or wget to download the Tailwind CLI (or set KB_TAILWIND_BIN)'
    fi
    mv -- "$bin.part" "$bin"
    chmod +x -- "$bin"
  fi
  if [ "$plat" = linux-x64 ]; then
    got="$(sha256_of "$bin")"
    if [ -n "$got" ] && [ "$got" != "$linux_x64_sha256" ]; then
      rm -f -- "$bin"
      fail "sha256 mismatch for $bin: got $got, want $linux_x64_sha256"
    fi
  else
    echo "web-css: warning: no pinned sha256 for $plat; the downloaded CLI is unverified" >&2
  fi
  echo "$bin"
}

bin="$(resolve_binary)"
tmp="$(mktemp "${TMPDIR:-/tmp}/kb-web-css.XXXXXX")"
"$bin" -i "$source" -o "$tmp.raw" --minify >/dev/null 2>"$tmp.err" || {
  cat "$tmp.err" >&2
  rm -f "$tmp.err"
  fail 'tailwind build failed'
}
rm -f "$tmp.err"
{
  echo "$header"
  cat "$tmp.raw"
} >"$tmp"

case "$mode" in
  build)
    mv -- "$tmp" "$target"
    tmp=''
    echo "web-css: wrote $target"
    ;;
  check)
    [ -f "$target" ] || fail "$target is missing; run scripts/build-web-css.sh"
    cmp -s -- "$tmp" "$target" || fail "$target is stale; run scripts/build-web-css.sh"
    echo 'web-css: pass'
    ;;
esac
